"""Shared test fixtures for staged_qwen3_5_scivqa tests."""

import json
import tempfile
from pathlib import Path
from unittest.mock import MagicMock

import pytest


@pytest.fixture
def mock_tokenizer():
    """Create a mock tokenizer that counts tokens by splitting on whitespace."""
    tokenizer = MagicMock()
    tokenizer.encode = lambda text, add_special_tokens=False: text.split()
    return tokenizer


@pytest.fixture
def sample_annotation():
    """Create a sample figure annotation dict matching the competition schema."""
    return {
        "sample_id": "test_paper/fig1",
        "classification": {"a": "line_chart"},
        "summarization": {"a": "The growth rate increases with temperature."},
        "data_extraction": {
            "a": "Temperature (C),Growth Rate (nm/cycle);100,0.5;150,0.8;200,0.9"
        },
        "vqa": {
            "a": [
                {
                    "question_type": "Comparative/Trend",
                    "questions": "At what temperature does the maximum growth rate occur?",
                    "answer_type": "Factoid",
                    "answer": "200 C",
                },
                {
                    "question_type": "Process-Oriented",
                    "questions": "Does growth rate saturate above 150 C?",
                    "answer_type": "Yes/No",
                    "answer": "Yes",
                },
            ]
        },
        "bbox": {
            "a": {"x": 0, "y": 0, "width": 100, "height": 100},
        },
    }


@pytest.fixture
def sample_content_json():
    """Create a sample content.json structure."""
    return [
        {"type": "text", "text": "Introduction paragraph before the figure."},
        {"type": "text", "text": "Second paragraph before the figure."},
        {
            "type": "image",
            "img_path": "images/fig1.jpg",
            "img_caption": ["Figure 1: Growth rate vs temperature."],
        },
        {"type": "text", "text": "First paragraph after the figure."},
        {"type": "text", "text": "Second paragraph after the figure."},
    ]


@pytest.fixture
def tmp_data_dir(sample_annotation, sample_content_json):
    """Create a temporary directory with sample competition data."""
    with tempfile.TemporaryDirectory() as tmpdir:
        base = Path(tmpdir)
        images_dir = base / "test_paper" / "images"
        images_dir.mkdir(parents=True)

        # Write annotation JSON
        with open(images_dir / "fig1.json", "w") as f:
            json.dump(sample_annotation, f)

        # Write content.json
        with open(base / "test_paper" / "content.json", "w") as f:
            json.dump(sample_content_json, f)

        # Create a minimal JPEG file
        # Minimal valid JPEG: SOI + APP0 + minimal data + EOI
        jpeg_data = bytes(
            [
                0xFF,
                0xD8,
                0xFF,
                0xE0,
                0x00,
                0x10,
                0x4A,
                0x46,
                0x49,
                0x46,
                0x00,
                0x01,
                0x01,
                0x00,
                0x00,
                0x01,
                0x00,
                0x01,
                0x00,
                0x00,
                0xFF,
                0xDB,
                0x00,
                0x43,
                0x00,
                0x08,
                0x06,
                0x06,
                0x07,
                0x06,
                0x05,
                0x08,
                0x07,
                0x07,
                0x07,
                0x09,
                0x09,
                0x08,
                0x0A,
                0x0C,
                0x14,
                0x0D,
                0x0C,
                0x0B,
                0x0B,
                0x0C,
                0x19,
                0x12,
                0x13,
                0x0F,
                0x14,
                0x1D,
                0x1A,
                0x1F,
                0x1E,
                0x1D,
                0x1A,
                0x1C,
                0x1C,
                0x20,
                0x24,
                0x2E,
                0x27,
                0x20,
                0x22,
                0x2C,
                0x23,
                0x1C,
                0x1C,
                0x28,
                0x37,
                0x29,
                0x2C,
                0x30,
                0x31,
                0x34,
                0x34,
                0x34,
                0x1F,
                0x27,
                0x39,
                0x3D,
                0x38,
                0x32,
                0x3C,
                0x2E,
                0x33,
                0x34,
                0x32,
                0xFF,
                0xC0,
                0x00,
                0x0B,
                0x08,
                0x00,
                0x01,
                0x00,
                0x01,
                0x01,
                0x01,
                0x11,
                0x00,
                0xFF,
                0xC4,
                0x00,
                0x1F,
                0x00,
                0x00,
                0x01,
                0x05,
                0x01,
                0x01,
                0x01,
                0x01,
                0x01,
                0x01,
                0x00,
                0x00,
                0x00,
                0x00,
                0x00,
                0x00,
                0x00,
                0x00,
                0x01,
                0x02,
                0x03,
                0x04,
                0x05,
                0x06,
                0x07,
                0x08,
                0x09,
                0x0A,
                0x0B,
                0xFF,
                0xC4,
                0x00,
                0xB5,
                0x10,
                0x00,
                0x02,
                0x01,
                0x03,
                0x03,
                0x02,
                0x04,
                0x03,
                0x05,
                0x05,
                0x04,
                0x04,
                0x00,
                0x00,
                0x01,
                0x7D,
                0x01,
                0x02,
                0x03,
                0x00,
                0x04,
                0x11,
                0x05,
                0x12,
                0x21,
                0x31,
                0x41,
                0x06,
                0x13,
                0x51,
                0x61,
                0x07,
                0x22,
                0x71,
                0x14,
                0x32,
                0x81,
                0x91,
                0xA1,
                0x08,
                0x23,
                0x42,
                0xB1,
                0xC1,
                0x15,
                0x52,
                0xD1,
                0xF0,
                0x24,
                0x33,
                0x62,
                0x72,
                0x82,
                0x09,
                0x0A,
                0x16,
                0x17,
                0x18,
                0x19,
                0x1A,
                0x25,
                0x26,
                0x27,
                0x28,
                0x29,
                0x2A,
                0x34,
                0x35,
                0x36,
                0x37,
                0x38,
                0x39,
                0x3A,
                0x43,
                0x44,
                0x45,
                0x46,
                0x47,
                0x48,
                0x49,
                0x4A,
                0x53,
                0x54,
                0x55,
                0x56,
                0x57,
                0x58,
                0x59,
                0x5A,
                0x63,
                0x64,
                0x65,
                0x66,
                0x67,
                0x68,
                0x69,
                0x6A,
                0x73,
                0x74,
                0x75,
                0x76,
                0x77,
                0x78,
                0x79,
                0x7A,
                0x83,
                0x84,
                0x85,
                0x86,
                0x87,
                0x88,
                0x89,
                0x8A,
                0x92,
                0x93,
                0x94,
                0x95,
                0x96,
                0x97,
                0x98,
                0x99,
                0x9A,
                0xA2,
                0xA3,
                0xA4,
                0xA5,
                0xA6,
                0xA7,
                0xA8,
                0xA9,
                0xAA,
                0xB2,
                0xB3,
                0xB4,
                0xB5,
                0xB6,
                0xB7,
                0xB8,
                0xB9,
                0xBA,
                0xC2,
                0xC3,
                0xC4,
                0xC5,
                0xC6,
                0xC7,
                0xC8,
                0xC9,
                0xCA,
                0xD2,
                0xD3,
                0xD4,
                0xD5,
                0xD6,
                0xD7,
                0xD8,
                0xD9,
                0xDA,
                0xE1,
                0xE2,
                0xE3,
                0xE4,
                0xE5,
                0xE6,
                0xE7,
                0xE8,
                0xE9,
                0xEA,
                0xF1,
                0xF2,
                0xF3,
                0xF4,
                0xF5,
                0xF6,
                0xF7,
                0xF8,
                0xF9,
                0xFA,
                0xFF,
                0xDA,
                0x00,
                0x08,
                0x01,
                0x01,
                0x00,
                0x00,
                0x3F,
                0x00,
                0xFB,
                0xD5,
                0xDB,
                0x20,
                0xB8,
                0xF8,
                0x53,
                0xC5,
                0xFF,
                0xD9,
            ]
        )
        with open(images_dir / "fig1.jpg", "wb") as f:
            f.write(jpeg_data)

        yield base
